# Preprocessing 

In [21]:
# Import modules
import pandas as pd
import numpy as np
from sklearn.impute import SimpleImputer as si
from sklearn.preprocessing import LabelEncoder, OneHotEncoder, MinMaxScaler 
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix

In [22]:
# Loading the dataset
data = pd.read_csv("Cancer_Data.csv")
#display(data.head(n=100))

In [23]:
# Divide the data into input and output
x = data.iloc[:,:-1].values
y = data.iloc[:,-1].values

In [24]:
# Replace missing data with the average of the columns values
imputer = si(missing_values=np.nan,strategy='mean')

x[:,1:33]=imputer.fit_transform(x[:,1:33])

In [6]:
# Encoding the output to 0s and 1s
lb=LabelEncoder()
y=lb.fit_transform(y)

In [7]:
# Scaling the input 
sc=MinMaxScaler()
x[:,1:]=sc.fit_transform(x[:,1:])

In [8]:
# Splitting the dataset into the Training set and Test set
x_train,x_test,y_train,y_test=train_test_split(x,y,train_size=.8,random_state=0)

In [20]:
# models
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import confusion_matrix

random = RandomForestClassifier(random_state=0)
DT = DecisionTreeClassifier(random_state=0)
Naive = GaussianNB()

clfs = [random, DT, Naive]
pred = {}
cm = {}

for clf in clfs:
    # Fitiing
    clf.fit(x_train, y_train)
    
    # Prediction
    pred[clf] = clf.predict(x_test)
    
    # Making the Confusion Matrix
    cm[clf] = confusion_matrix(y_test, pred[clf])
    
for name, cm in (cm.items()):
    print(name, ":\n", cm)

RandomForestClassifier(random_state=0) :
 [[66  1]
 [ 2 45]]
DecisionTreeClassifier(random_state=0) :
 [[59  8]
 [ 3 44]]
GaussianNB() :
 [[66  1]
 [45  2]]


In [31]:
data.iloc[:,-1] = lb.fit_transform(data.iloc[:, -1])
data.iloc[:,1:31] =imputer.fit_transform(data.iloc[:,1:31])
display(data.head(n=5))

id  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302        17.99         10.38          122.80     1001.0   
1    842517        20.57         17.77          132.90     1326.0   
2  84300903        19.69         21.25          130.00     1203.0   
3  84348301        11.42         20.38           77.58      386.1   
4  84358402        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  texture_worst  perimeter_worst  area_worst  \
0         0.2419  ...          17.33           184.60      2019.0   
1         0.1812  ...          23.41           158.80      1956.0   
2         0.2069  ...          25.53           152.50      1709.0   
3         0.2597  ...          26.50            98.87       567.7   
4         0.1809  ...          16.67           152.20      1575.0   

   smoothness_worst  compactness_worst  concavity_worst  concave points_worst  \
0            0.1622             0.6656           0.7119                0.2654   
1            0.1238             0.1866           0.2416                0.1860   
2            0.1444             0.4245           0.4504                0.2430   
3            0.2098             0.8663           0.6869                0.2575   
4            0.1374             0.2050           0.4000                0.1625   

   symmetry_worst  fractal_dimension_worst  diagnosis  
0          0.4601                  0.11890          1  
1          0.2750                  0.08902          1  
2          0.3613                  0.08758          1  
3          0.6638                  0.17300          1  
4          0.2364                  0.07678          1  

[5 rows x 32 columns]

In [33]:
# Kmeans
from sklearn.cluster import KMeans

kmeans = KMeans(n_clusters=2, random_state=0, n_init="auto").fit(data)
Kmeans_pred = Kmeans.predict(x_test)
cm["Kmeans"] = confusion_matrix(y_test, pred[clf])

TypeError: '<=' not supported between instances of 'str' and 'int'