# Preprocessing 

In [21]:
# Import modules
import pandas as pd
import numpy as np
from sklearn.impute import SimpleImputer as si
from sklearn.preprocessing import LabelEncoder, OneHotEncoder, MinMaxScaler 
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix

In [22]:
# Loading the dataset
data = pd.read_csv("Cancer_Data.csv")
#display(data.head(n=100))

In [23]:
# Divide the data into input and output
x = data.iloc[:,:-1].values
y = data.iloc[:,-1].values

In [34]:
# Replace missing data with the average of the columns values
imputer = si(missing_values=np.nan,strategy='mean')

x=imputer.fit_transform(x)

In [35]:
# Encoding the output to 0s and 1s
lb=LabelEncoder()
y=lb.fit_transform(y)

In [36]:
# Scaling the input 
sc=MinMaxScaler()
x[:,1:]=sc.fit_transform(x[:,1:])

In [37]:
# Splitting the dataset into the Training set and Test set
x_train,x_test,y_train,y_test=train_test_split(x,y,train_size=.8,random_state=0)

In [38]:
# models
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import confusion_matrix

random = RandomForestClassifier(random_state=0)
DT = DecisionTreeClassifier(random_state=0)
Naive = GaussianNB()

clfs = [random, DT, Naive]
pred = {}
cm = {}

for clf in clfs:
    # Fitiing
    clf.fit(x_train, y_train)
    
    # Prediction
    pred[clf] = clf.predict(x_test)
    
    # Making the Confusion Matrix
    cm[clf] = confusion_matrix(y_test, pred[clf])
    
for name, cm in (cm.items()):
    print(name, ":\n", cm)

RandomForestClassifier(random_state=0) :
 [[66  1]
 [ 2 45]]
DecisionTreeClassifier(random_state=0) :
 [[59  8]
 [ 3 44]]
GaussianNB() :
 [[66  1]
 [45  2]]


In [39]:
# Preparing data for clustering
data.iloc[:,-1] = lb.fit_transform(data.iloc[:, -1])
data.iloc[:,1:31] =imputer.fit_transform(data.iloc[:,1:31])
#display(data.head(n=5))

In [33]:
# Kmeans
from sklearn.cluster import KMeans

kmeans = KMeans(n_clusters=2, random_state=0, n_init="auto").fit(data)
Kmeans_pred = Kmeans.predict(x_test)
cm["Kmeans"] = confusion_matrix(y_test, pred[clf])

TypeError: '<=' not supported between instances of 'str' and 'int'