# Preprocessing 

In [2]:
# Import modules
import pandas as pd
import numpy as np
from sklearn.impute import SimpleImputer as si
from sklearn.preprocessing import LabelEncoder, OneHotEncoder, MinMaxScaler 
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix

In [3]:
# Loading the dataset
data = pd.read_csv("Cancer_Data.csv")
#display(data.head(n=100))

In [4]:
# Divide the data into input and output
x = data.iloc[:,:-1].values
y = data.iloc[:,-1].values

In [5]:
# Replace missing data with the average of the columns values
imputer = si(missing_values=np.nan,strategy='mean')

x[:,1:33]=imputer.fit_transform(x[:,1:33])

In [6]:
# Encoding the output to 0s and 1s
lb=LabelEncoder()
y=lb.fit_transform(y)

In [7]:
# Scaling the input 
sc=MinMaxScaler()
x[:,1:]=sc.fit_transform(x[:,1:])

In [8]:
# Splitting the dataset into the Training set and Test set
x_train,x_test,y_train,y_test=train_test_split(x,y,train_size=.8,random_state=0)

In [14]:
# models
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import confusion_matrix

random = RandomForestClassifier(random_state=0)
DT = DecisionTreeClassifier(random_state=0)
Naive = GaussianNB()

clfs = [random, DT, Naive]
pred = {}
cm = {}
for clf in clfs:
    # Fitiing
    clf.fit(x_train, y_train)
    pred[clf] = clf.predict(x_test)
    
    # Making the Confusion Matrix
    cm[clf] = confusion_matrix(y_test, pred[clf])
for name, cm in (cm.items()):
    print(name, ":\n", cm)

RandomForestClassifier(random_state=0) :
 [[66  1]
 [ 2 45]]
DecisionTreeClassifier(random_state=0) :
 [[59  8]
 [ 3 44]]
GaussianNB() :
 [[66  1]
 [45  2]]
